# Generated by Django 4.2.1 on 2023-06-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('cpf', models.TextField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acerval.item')),
                ('titulo', models.TextField(max_length=100)),
                ('autor', models.TextField(blank=True, max_length=100)),
                ('ano', models.IntegerField(blank=True)),
            ],
            bases=('acerval.item',),
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acerval.item')),
                ('nome', models.TextField(max_length=100)),
            ],
            bases=('acerval.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acerval.usuario'),
        ),
        migrations.AddField(
            model_name='item',
            name='emprestado_para',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acerval.contato'),
        ),
        migrations.AddField(
            model_name='contato',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acerval.usuario'),
        ),
    ]
