# Generated by Django 4.2.1 on 2023-07-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("acerval", "0002_alter_contato_contato_de"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="emprestado_para",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="acerval.contato",
            ),
        ),
    ]
